messages:
  success: "success"
  notice: "notice"
framgia:
  more_tool: "http://education.framgia.vn/tools"
  phone_text: "(+84) 4 3795 5417"
  phone_number: +84437955417
  email: "faa@framgia.com"
  facebook: "https://facebook.com/FramgiaVietnam/"
home:
  courses_limit: 10
  trainers_limit: 10
  trainer_quote_limit: 50
courses:
  length_description: 200
  per_page: 12
  popular: 4
  max_name_length: 255
  min_name_length: 3
  max_description_length: 1000
  min_description_length: 10
feedbacks:
  max_name_length: 127
  max_email_length: 127
  max_subject_length: 255
  max_content_length: 1023
  max_phone_length: 15
trainers:
  per_page: 20
certifications:
  min_name_length: 2
  max_name_length: 255
  max_description_length: 500
registrations:
  max_name_length: 127
  max_email_length: 127
  max_phone_length: 15
  max_address_length: 255
news:
  per_page: 20
  length_content: 320
  latest_news: 4
  popular_tags: 10
  max_title_length: 255
image_default: "/assets/course_default.jpg"
news_category:
  min_name_length: 2
  max_name_length: 30
  max_description_length: 500
users:
  min_name_length: 2
  max_name_length: 30
  max_quote_length: 500
  min_phone_length: 10
  max_phone_length: 15
course_category:
  max_name_length: 255
course_registrations:
  reject: "reject"
course_schedules:
  per_page: 10
